### ISSUE TITLE
[앤서블철저입문] 2장 앤서블 설치

### ISSUE THREAD

**Issue by sweaterr** [sweaterr/start_ansible#2]
# 맥 OS 에 설치

학습을 위해서 설치 시 맥북에서 하는게 제일 쉬울듯

```
brew cask install virtualbox vagrant
```

```
vagrant init bento/centos-7.2
```

```
vagrant up
```

**Comment by sweaterr** [comment]
# 인벤터리 파일 작성

hosts 파일 생성 

```
vagrant-machine ansible_host=127.0.0.1 ansible_port=2222 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key

```

ansible.cfg 파일 생성

```
[defaults]
host_key_checking = False
```

**Comment by sweaterr** [comment]
## 플레이북 파일 작성

`site.yml` 파일 작성

```
---
- name: 플레이북 튜토리얼
  hosts: all
  become: true
  tasks:
    - name: libselinux-python 설치
      yum:
        name: libselinux-python
        state: present

    - name: EPEL 리포지터리 설치
      yum:
        name: epel-release
        state: present

    - name: 엔진엑스 설치
      yum:
        name: nginx
        state: present

    - name: 엔진엑스 서비스 시작과 자동 시작 설정
      service:
        name: nginx
        state: started
        enabled: true

```
